services:
  ui:
    image: ghcr.io/glourb/glourbee-ui:latest
    restart: always
    depends_on:
      - worker
      - db
    ports:
      - "8501:8501"
    environment:
      - GLOURBEE_DATASTORE=$GLOURBEE_DATASTORE
      - GLOURBEE_BROKER_URL=$GLOURBEE_BROKER_URL
      - GLOURBEE_DB_URI=$GLOURBEE_DB_URI
      - WEBDAV_USER=$WEBDAV_USER
      - WEBDAV_PASSWORD=$WEBDAV_PASSWORD
      - WEBDAV_URL=$WEBDAV_URL
    volumes:
      - data:/data
      - ./glourbee:/app/glourbee # dev only
      - ./ui:/app/ui # dev only

  worker:
    image: ghcr.io/glourb/glourbee-ui:latest
    restart: always
    depends_on:
      - broker
      - db
    command: [celery, -A, glourbee.worker, worker, -c, "1", -l, INFO]
    environment:
      - GLOURBEE_DATASTORE=$GLOURBEE_DATASTORE
      - GLOURBEE_BROKER_URL=$GLOURBEE_BROKER_URL
      - GLOURBEE_DB_URI=$GLOURBEE_DB_URI
      - GLOURBEE_EMAIL_FROM=$GLOURBEE_EMAIL_FROM
      - GLOURBEE_EMAIL_SERVER=$GLOURBEE_EMAIL_SERVER
      - GLOURBEE_EMAIL_PORT=$GLOURBEE_EMAIL_PORT
      - GLOURBEE_EMAIL_USER=$GLOURBEE_EMAIL_USER
      - GLOURBEE_EMAIL_PASSWORD=$GLOURBEE_EMAIL_PASSWORD
      - GLOURBEE_EE_JSONKEY=$GLOURBEE_EE_JSONKEY
    healthcheck: 
        test: ["CMD-SHELL", "celery -A glourbee.worker inspect ping --destination celery@$$HOSTNAME"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s
    volumes:
      - data:/data
      - ./ee-glourb-718927cf3d80.json:/app/earthengine-key.json:ro
      - ./glourbee:/app/glourbee # dev only

  webdav:
    image: ghcr.io/hacdias/webdav:latest
    restart: always
    ports: 
      - "6060:6060"
    volumes:
      - data:/data
      - ./webdav-config.yml:/config.yml:ro
    environment:
      - WEBDAV_USER=$WEBDAV_USER
      - WEBDAV_PASSWORD=$WEBDAV_PASSWORD

  broker:
    image: redis:latest
    restart: always

  db:
    image: postgis/postgis:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432" # dev only
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  data:
  db-data: