services:
  ui:
    image: ghcr.io/evs-gis/glourbee-ui:latest
    restart: always
    depends_on:
      - worker
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GLOURBEE_DATASTORE=$GLOURBEE_DATASTORE
      - GLOURBEE_BROKER_URL=$GLOURBEE_BROKER_URL
      - GLOURBEE_DB_URI=$GLOURBEE_DB_URI
    volumes:
      - data:/data
      - ./ui:/app/ui:ro # For dev only
      - ./glourbee:/app/glourbee:ro # For dev only

  worker:
    image: ghcr.io/evs-gis/glourbee-ui:latest
    restart: always
    depends_on:
      - broker
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [celery, -A, glourbee.worker, worker, -c, "1", -l, INFO]
    environment:
      - GLOURBEE_DATASTORE=$GLOURBEE_DATASTORE
      - GLOURBEE_BROKER_URL=$GLOURBEE_BROKER_URL
      - GLOURBEE_DB_URI=$GLOURBEE_DB_URI
      - GLOURBEE_EMAIL_FROM=$GLOURBEE_EMAIL_FROM
      - GLOURBEE_EMAIL_SERVER=$GLOURBEE_EMAIL_SERVER
      - GLOURBEE_EMAIL_PORT=$GLOURBEE_EMAIL_PORT
      - GLOURBEE_EMAIL_USER=$GLOURBEE_EMAIL_USER
      - GLOURBEE_EMAIL_PASSWORD=$GLOURBEE_EMAIL_PASSWORD
      - FILESENDER_SCRIPT=$FILESENDER_SCRIPT
      - FILESENDER_BASE_URL=$FILESENDER_BASE_URL
      - FILESENDER_USERNAME=$FILESENDER_USERNAME
      - FILESENDER_APIKEY=$FILESENDER_APIKEY
      - FILESENDER_FROM=$FILESENDER_FROM
    volumes:
      - data:/data
      - ./ee-glourb-718927cf3d80.json:/app/earthengine-key.json:ro
      - ./ui:/app/ui:ro # For dev only
      - ./glourbee:/app/glourbee:ro # For dev only

  broker:
    image: redis:latest
    restart: always

  db:
    image: postgis/postgis:latest
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # For dev only

volumes:
  data:
  db-data: