[theme]
base="light"
primaryColor="#2c7125"
secondaryBackgroundColor="#cbeac7"

[logger]
level = 'info'

[client]
showErrorDetails = "none"
toolbarMode = "auto"

[runner]
enforceSerializableSessionState = true

[server]
folderWatchList = ["/app/glourbee"]
cookieSecret = "dontforgettochangeit"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
